steps:

# Build an image in Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/notes-app-backend'
  - '.'

# Deploy an image from Container Registry to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'notes-app-backend'
  - '--image'
  - 'gcr.io/$PROJECT_ID/notes-app-backend'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'

images:
- 'gcr.io/$PROJECT_ID/notes-app-backend'